# Generated by Django 3.1.2 on 2020-11-26 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201126_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emailid',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(),
        ),
    ]
