# Generated by Django 3.1.2 on 2020-11-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_employee_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emailid',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='empid',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
