# Generated by Django 3.1.2 on 2020-11-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201126_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
